A2lixDemoTranslationBundle_Backend:
    resource: "@A2lixDemoTranslationBundle/Controller/Backend/"
    type:     annotation
    prefix:   /backend

A2lixDemoTranslationBundle_Frontend:
    resource: "@A2lixDemoTranslationBundle/Controller/Frontend/"
    type:     annotation
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
